-- ============================================================================
-- Baseline migration — initializes the donation-platform schema.
-- ============================================================================
-- Created: 2026-09-02
-- Why this is "init" and not the project's first migration:
--   The repo previously had no `prisma/migrations/` directory tracked in git
--   (the files were deleted at some point between d3b8f82 and HEAD). The dev
--   DB has a `_prisma_migrations` row for `20260820200835_init`, but the
--   corresponding SQL is gone. This `init` migration:
--
--     1. Creates the `_prisma_migrations` table if it doesn't exist (prod
--        was bootstrapped via `prisma db push`, so it's missing).
--     2. Creates every enum, table, index, and FK from the current
--        `prisma/schema.prisma` using ONLY idempotent statements
--        (`CREATE ... IF NOT EXISTS`, `ADD COLUMN IF NOT EXISTS`,
--        `CREATE INDEX IF NOT EXISTS`, `DO $$ ... $$` for constraint
--        additions). This means the migration is safe to apply against
--        any DB state — a fully-empty DB, a partially-migrated DB
--        (like prod), or a freshly-reset DB. It will only add what's
--        missing and never error on pre-existing objects.
--
--   Future schema changes will produce normal non-idempotent migrations
--   via `pnpm prisma migrate dev --name <descriptive>`. The idempotency
--   here is purely a one-time concern to backfill prod into alignment
--   with the schema in source control.
--
-- DO NOT EDIT THIS FILE once it has been applied in production. Subsequent
-- schema changes go in new migrations. See CONTRIBUTING.md §Testing
-- Requirements and the schema-change checklist.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 0. Prisma migrations table (needed by `prisma migrate deploy` itself).
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "_prisma_migrations" (
    "id"                    TEXT PRIMARY KEY,
    "checksum"              TEXT NOT NULL,
    "finished_at"           TIMESTAMP(3),
    "migration_name"        TEXT NOT NULL,
    "logs"                  TEXT,
    "rolled_back_at"        TIMESTAMP(3),
    "started_at"            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "applied_steps_count"   INTEGER NOT NULL DEFAULT 0
);

-- ----------------------------------------------------------------------------
-- 1. Enums (create only if missing; add any new values to existing types).
-- ----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'UserRole') THEN
        CREATE TYPE "UserRole" AS ENUM ('USER', 'ADMIN');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'DonationStatus') THEN
        CREATE TYPE "DonationStatus" AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'CANCELLED');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'DonationPurpose') THEN
        CREATE TYPE "DonationPurpose" AS ENUM ('GENERAL_FUND', 'EDUCATION', 'MEDICAL', 'EMERGENCY');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Language') THEN
        CREATE TYPE "Language" AS ENUM ('BN', 'EN');
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'AuditSeverity') THEN
        CREATE TYPE "AuditSeverity" AS ENUM ('INFO', 'WARNING', 'CRITICAL');
    END IF;
END
$$;

-- ----------------------------------------------------------------------------
-- 2. Tables. `CREATE TABLE IF NOT EXISTS` is used so the migration is
-- safe against DBs that were bootstrapped via `prisma db push` (prod) and
-- already have these tables with older schemas.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS "Account" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "provider" TEXT NOT NULL,
    "providerAccountId" TEXT NOT NULL,
    "refresh_token" TEXT,
    "access_token" TEXT,
    "expires_at" INTEGER,
    "token_type" TEXT,
    "scope" TEXT,
    "id_token" TEXT,
    "session_state" TEXT,
    CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Session" (
    "id" TEXT NOT NULL,
    "sessionToken" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "Session_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "VerificationToken" (
    "identifier" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "expires" TIMESTAMP(3) NOT NULL
);

CREATE TABLE IF NOT EXISTS "User" (
    "id" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "emailVerified" TIMESTAMP(3),
    "name" TEXT NOT NULL,
    "avatarUrl" TEXT,
    "phone" TEXT,
    "role" "UserRole" NOT NULL DEFAULT 'USER',
    "languagePref" "Language" NOT NULL DEFAULT 'BN',
    "isBanned" BOOLEAN NOT NULL DEFAULT false,
    "bannedAt" TIMESTAMP(3),
    "bannedReason" TEXT,
    "profileCompleted" BOOLEAN NOT NULL DEFAULT false,
    "lastLoginAt" TIMESTAMP(3),
    "deletedAt" TIMESTAMP(3),
    "tokenVersion" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "Donation" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "amount" DECIMAL(10,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'BDT',
    "purpose" "DonationPurpose" NOT NULL,
    "status" "DonationStatus" NOT NULL DEFAULT 'PENDING',
    "isAnonymous" BOOLEAN NOT NULL DEFAULT false,
    "bkashPaymentId" TEXT,
    "bkashTransactionId" TEXT,
    "paymentMethod" TEXT DEFAULT 'manual_bkash',
    "failureReason" TEXT,
    "trxId" TEXT,
    "senderPhone" TEXT,
    "trxSubmittedAt" TIMESTAMP(3),
    "reviewedById" TEXT,
    "reviewedAt" TIMESTAMP(3),
    "adminNote" TEXT,
    "metadata" JSONB,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "completedAt" TIMESTAMP(3),
    CONSTRAINT "Donation_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "AuditLog" (
    "id" TEXT NOT NULL,
    "userId" TEXT,
    "action" TEXT NOT NULL,
    "resource" TEXT,
    "details" JSONB,
    "ipAddress" TEXT,
    "userAgent" TEXT,
    "status" TEXT NOT NULL DEFAULT 'SUCCESS',
    "severity" "AuditSeverity" NOT NULL DEFAULT 'INFO',
    "correlationId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "UserSettings" (
    "userId" TEXT NOT NULL,
    "emailNotifications" BOOLEAN NOT NULL DEFAULT true,
    "donationReceipts" BOOLEAN NOT NULL DEFAULT true,
    "theme" TEXT NOT NULL DEFAULT 'system',
    CONSTRAINT "UserSettings_pkey" PRIMARY KEY ("userId")
);

-- ----------------------------------------------------------------------------
-- 3. Columns. For tables that pre-exist in prod (because the schema has
-- been alive for a while), `CREATE TABLE IF NOT EXISTS` is a no-op and the
-- columns below are what actually backfills the drift. Every column uses
-- `ADD COLUMN IF NOT EXISTS` so re-running the migration is harmless.
-- ----------------------------------------------------------------------------
-- Account: no additive columns beyond the table definition.
-- Session: no additive columns.
-- VerificationToken: no additive columns.

-- User: ensure deletedAt + tokenVersion exist (added in 364adf9).
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "deletedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "tokenVersion" INTEGER NOT NULL DEFAULT 0;

-- Donation: manual bKash fields (trxId/senderPhone/trxSubmittedAt + admin
-- review trail — added in 364adf9). These are the columns the failing
-- /api/donations/history route selects but prod doesn't have.
ALTER TABLE "Donation" ADD COLUMN IF NOT EXISTS "trxId" TEXT;
ALTER TABLE "Donation" ADD COLUMN IF NOT EXISTS "senderPhone" TEXT;
ALTER TABLE "Donation" ADD COLUMN IF NOT EXISTS "trxSubmittedAt" TIMESTAMP(3);
ALTER TABLE "Donation" ADD COLUMN IF NOT EXISTS "reviewedById" TEXT;
ALTER TABLE "Donation" ADD COLUMN IF NOT EXISTS "reviewedAt" TIMESTAMP(3);
ALTER TABLE "Donation" ADD COLUMN IF NOT EXISTS "adminNote" TEXT;
-- Also make sure the `failureReason` and `paymentMethod` defaults are right.
-- (No-op if already correct; `SET DEFAULT` is idempotent.)
ALTER TABLE "Donation" ALTER COLUMN "paymentMethod" SET DEFAULT 'manual_bkash';

-- AuditLog: severity + correlationId (used by fail() persistError).
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "severity" "AuditSeverity" NOT NULL DEFAULT 'INFO';
ALTER TABLE "AuditLog" ADD COLUMN IF NOT EXISTS "correlationId" TEXT;

-- ----------------------------------------------------------------------------
-- 4. Indexes (CREATE INDEX IF NOT EXISTS — safe to re-run).
-- ----------------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS "Account_userId_idx" ON "Account"("userId");
CREATE UNIQUE INDEX IF NOT EXISTS "Account_provider_providerAccountId_key" ON "Account"("provider", "providerAccountId");

CREATE UNIQUE INDEX IF NOT EXISTS "Session_sessionToken_key" ON "Session"("sessionToken");
CREATE INDEX IF NOT EXISTS "Session_userId_idx" ON "Session"("userId");

CREATE UNIQUE INDEX IF NOT EXISTS "VerificationToken_token_key" ON "VerificationToken"("token");
CREATE UNIQUE INDEX IF NOT EXISTS "VerificationToken_identifier_token_key" ON "VerificationToken"("identifier", "token");

CREATE UNIQUE INDEX IF NOT EXISTS "User_email_key" ON "User"("email");
CREATE INDEX IF NOT EXISTS "User_email_idx" ON "User"("email");
CREATE INDEX IF NOT EXISTS "User_role_idx" ON "User"("role");
CREATE INDEX IF NOT EXISTS "User_isBanned_idx" ON "User"("isBanned");
CREATE INDEX IF NOT EXISTS "User_createdAt_idx" ON "User"("createdAt");
CREATE INDEX IF NOT EXISTS "User_deletedAt_idx" ON "User"("deletedAt");

CREATE UNIQUE INDEX IF NOT EXISTS "Donation_bkashPaymentId_key" ON "Donation"("bkashPaymentId");
CREATE UNIQUE INDEX IF NOT EXISTS "Donation_bkashTransactionId_key" ON "Donation"("bkashTransactionId");
CREATE INDEX IF NOT EXISTS "Donation_userId_idx" ON "Donation"("userId");
CREATE INDEX IF NOT EXISTS "Donation_status_idx" ON "Donation"("status");
CREATE INDEX IF NOT EXISTS "Donation_createdAt_idx" ON "Donation"("createdAt");
CREATE INDEX IF NOT EXISTS "Donation_userId_status_createdAt_idx" ON "Donation"("userId", "status", "createdAt");
CREATE INDEX IF NOT EXISTS "Donation_bkashPaymentId_idx" ON "Donation"("bkashPaymentId");
CREATE INDEX IF NOT EXISTS "Donation_status_createdAt_idx" ON "Donation"("status", "createdAt");
CREATE INDEX IF NOT EXISTS "Donation_reviewedById_idx" ON "Donation"("reviewedById");

CREATE INDEX IF NOT EXISTS "AuditLog_userId_idx" ON "AuditLog"("userId");
CREATE INDEX IF NOT EXISTS "AuditLog_action_idx" ON "AuditLog"("action");
CREATE INDEX IF NOT EXISTS "AuditLog_createdAt_idx" ON "AuditLog"("createdAt");
CREATE INDEX IF NOT EXISTS "AuditLog_severity_idx" ON "AuditLog"("severity");
CREATE INDEX IF NOT EXISTS "AuditLog_correlationId_idx" ON "AuditLog"("correlationId");

-- ----------------------------------------------------------------------------
-- 5. Foreign keys. Use DO $$ to add the constraint only if it doesn't
-- exist yet (Postgres has no `ADD CONSTRAINT IF NOT EXISTS`).
-- ----------------------------------------------------------------------------
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'Account_userId_fkey'
    ) THEN
        ALTER TABLE "Account"
            ADD CONSTRAINT "Account_userId_fkey"
            FOREIGN KEY ("userId") REFERENCES "User"("id")
            ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'Session_userId_fkey'
    ) THEN
        ALTER TABLE "Session"
            ADD CONSTRAINT "Session_userId_fkey"
            FOREIGN KEY ("userId") REFERENCES "User"("id")
            ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'Donation_userId_fkey'
    ) THEN
        ALTER TABLE "Donation"
            ADD CONSTRAINT "Donation_userId_fkey"
            FOREIGN KEY ("userId") REFERENCES "User"("id")
            ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'Donation_reviewedById_fkey'
    ) THEN
        ALTER TABLE "Donation"
            ADD CONSTRAINT "Donation_reviewedById_fkey"
            FOREIGN KEY ("reviewedById") REFERENCES "User"("id")
            ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'AuditLog_userId_fkey'
    ) THEN
        ALTER TABLE "AuditLog"
            ADD CONSTRAINT "AuditLog_userId_fkey"
            FOREIGN KEY ("userId") REFERENCES "User"("id")
            ON DELETE SET NULL ON UPDATE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'UserSettings_userId_fkey'
    ) THEN
        ALTER TABLE "UserSettings"
            ADD CONSTRAINT "UserSettings_userId_fkey"
            FOREIGN KEY ("userId") REFERENCES "User"("id")
            ON DELETE CASCADE ON UPDATE CASCADE;
    END IF;
END
$$;
