#!/bin/bash
# ============================================
# VPS Initial Setup Script
# ============================================
# Idempotent: safe to re-run. Configures a fresh Ubuntu VPS
# for the donation platform deployment.
#
# Usage:
#   sudo ./scripts/setup-vps.sh example.com admin@example.com
#
# Args:
#   $1 — domain name (default: example.com)
#   $2 — admin email for Let's Encrypt (default: admin@example.com)
# ============================================
set -euo pipefail

if [ "$(id -u)" -ne 0 ]; then
  echo "ERROR: Must run as root (use sudo)"
  exit 1
fi

DOMAIN="${1:-example.com}"
ADMIN_EMAIL="${2:-admin@${DOMAIN}}"
APP_DIR="/opt/donation-platform"
LOG_PREFIX="[setup-vps]"

log()  { echo "${LOG_PREFIX} $(date '+%F %T') $*"; }
fail() { echo "${LOG_PREFIX} ERROR: $*" >&2; exit 1; }

# ---------- System update ----------
log "Updating system packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y
apt-get install -y \
  curl wget git ca-certificates gnupg lsb-release \
  ufw fail2ban jq

# ---------- Docker (idempotent) ----------
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker..."
  curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
  sh /tmp/get-docker.sh
  rm -f /tmp/get-docker.sh
else
  log "Docker already installed: $(docker --version)"
fi

if ! docker compose version >/dev/null 2>&1; then
  log "Installing Docker Compose plugin..."
  apt-get install -y docker-compose-plugin
fi

# ---------- Certbot (idempotent) ----------
if ! command -v certbot >/dev/null 2>&1; then
  log "Installing Certbot..."
  apt-get install -y certbot
else
  log "Certbot already installed: $(certbot --version)"
fi

# ---------- AWS CLI for S3 backups ----------
if ! command -v aws >/dev/null 2>&1; then
  log "Installing AWS CLI..."
  curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/aws.zip
  (cd /tmp && unzip -q aws.zip && ./aws/install)
  rm -rf /tmp/aws /tmp/aws.zip
fi

# ---------- App directory ----------
log "Setting up app directory at $APP_DIR..."
mkdir -p "$APP_DIR"
mkdir -p "$APP_DIR/nginx/conf.d" "$APP_DIR/certbot/conf" "$APP_DIR/certbot/www"
mkdir -p "$APP_DIR/backups" "$APP_DIR/logs" "$APP_DIR/scripts"

# ---------- .env file (only if missing) ----------
ENV_FILE="$APP_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  log "Creating .env with placeholder values..."
  cat > "$ENV_FILE" <<EOF
# ============================================
# Donation Platform — Production Environment
# ============================================
# Generated by setup-vps.sh on $(date -u +%FT%TZ)
# Domain: $DOMAIN

# Application
NODE_ENV=production
NEXT_PUBLIC_URL=https://${DOMAIN}

# Database
POSTGRES_USER=donation
POSTGRES_PASSWORD=CHANGE_ME_$(openssl rand -hex 16)
POSTGRES_DB=donation

# NextAuth
NEXTAUTH_URL=https://${DOMAIN}
NEXTAUTH_SECRET=CHANGE_ME_$(openssl rand -hex 32)

# Google OAuth
GOOGLE_CLIENT_ID=CHANGE_ME
GOOGLE_CLIENT_SECRET=CHANGE_ME

# bKash Payment (sandbox by default — switch to production for live)
BKASH_BASE_URL=https://tokenized.pay.bka.sh/v1.2.0-beta/sandbox
BKASH_APP_KEY=CHANGE_ME
BKASH_APP_SECRET=CHANGE_ME
BKASH_USERNAME=CHANGE_ME
BKASH_PASSWORD=CHANGE_ME

# Cloudflare R2 (optional)
R2_ACCOUNT_ID=CHANGE_ME
R2_ACCESS_KEY_ID=CHANGE_ME
R2_SECRET_ACCESS_KEY=CHANGE_ME
R2_BUCKET_NAME=donation-platform

# Sentry (optional)
SENTRY_DSN=CHANGE_ME

# SendGrid (optional)
SENDGRID_API_KEY=CHANGE_ME
SENDGRID_FROM_EMAIL=noreply@${DOMAIN}

# Backups (S3)
S3_BUCKET=CHANGE_ME_s3://your-bucket/db-backups
AWS_REGION=ap-southeast-1
BACKUP_RETENTION_DAYS=30

# Slack alerts (optional)
SLACK_WEBHOOK_URL=CHANGE_ME
EOF
  chmod 600 "$ENV_FILE"
  log "Created $ENV_FILE (chmod 600). Edit credentials before deploying!"
else
  log "$ENV_FILE already exists — leaving untouched"
fi

# ---------- Firewall ----------
log "Configuring firewall (ufw)..."
ufw --force reset
ufw default deny incoming
ufw default allow outgoing
ufw allow 22/tcp comment "SSH"
ufw allow 80/tcp comment "HTTP"
ufw allow 443/tcp comment "HTTPS"
ufw --force enable

# ---------- Fail2ban ----------
log "Ensuring fail2ban is running..."
systemctl enable fail2ban
systemctl restart fail2ban || true

# ---------- Cron jobs ----------
log "Setting up cron jobs..."
CRON_TMP=$(mktemp)
crontab -l 2>/dev/null > "$CRON_TMP" || true

# Remove existing donation-platform lines first (idempotency)
sed -i '/donation-platform/d' "$CRON_TMP" 2>/dev/null || true

cat >> "$CRON_TMP" <<EOF
# Daily DB backup at 02:00
0 2 * * * cd ${APP_DIR} && /opt/donation-platform/scripts/backup-db.sh >> /var/log/donation-backup.log 2>&1

# Health check every 5 minutes
*/5 * * * * /opt/donation-platform/scripts/monitor.sh >> /var/log/donation-monitor.log 2>&1

# SSL renewal check weekly
0 3 * * 0 certbot renew --quiet
EOF
crontab "$CRON_TMP"
rm -f "$CRON_TMP"

# ---------- Docker permissions ----------
if id -u "ubuntu" >/dev/null 2>&1; then
  usermod -aG docker ubuntu
  log "Added 'ubuntu' to docker group"
fi

log ""
log "============================================"
log "✅ VPS setup complete!"
log "============================================"
log ""
log "Next steps:"
log "1. Edit ${ENV_FILE} with your real credentials"
log "2. Clone your repo into ${APP_DIR}:"
log "     cd ${APP_DIR} && git clone https://github.com/yourusername/donation-platform.git ."
log "3. Start the stack:"
log "     cd ${APP_DIR} && docker compose up -d"
log "4. Obtain SSL certificate:"
log "     docker compose run --rm certbot certonly --webroot -w /var/www/certbot -d ${DOMAIN} --email ${ADMIN_EMAIL} --agree-tos"
log "5. Restart nginx to pick up certs:"
log "     docker compose restart nginx"
log ""
log "Monitoring:"
log "  - Health:    curl -f https://${DOMAIN}/api/health"
log "  - Logs:      tail -f /var/log/donation-monitor.log"
log "  - Manual:    ${APP_DIR}/scripts/monitor.sh"
